{"error": null, "issues": [{"address": 3523, "code": "el3_ / welcomeFee_;\n\n        uint256 _ta", "debug": "The exception is triggered under the following conditions:\n\nstorage_3: 0x0\ncallvalue: 0x0\nstorage_11: 0xff00\nstorage_4: 0x0\ncalldatasize_NTS80: 0x3\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/NTS_Crypto_Deposit-2.sol", "function": "fallback", "lineno": 157, "title": "Exception state", "type": "Informational"}], "success": true}
