{"error": null, "issues": [{"address": 4582, "code": "   uint256 tokensMinted,\n        address ref1,", "debug": "callvalue: 0x93931c13e507cbbcbf74d9eee4fb920eeaef84aa5110428da2eddb017d5ebcdd\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Neutrino81_4: 0xb2c81e3be60b809eebca250ae5f3958de8241f3c0942692d3cecd1fd00743211\ncaller: 0xf43414abb5a05c3037910506571e4333e16a4bf4\nstorage_2: 0xbcbeb544a5fa3cfc86efaf9a8e1bccc1e95b40b00\ncalldata_Neutrino81_0: 0x31e9b2fc00000000000000000000000000000000000000000000000000000000\ncalldatasize_Neutrino81: 0x4\n", "description": "A possible integer overflow exists in the function `passInterest(address,uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/NTS_Crypto_Deposit-0.sol", "function": "passInterest(address,uint256,uint256)", "lineno": 247, "title": "Integer Overflow ", "type": "Warning"}, {"address": 6022, "code": "== admin || msg.sender == boss1 || msg.", "debug": "callvalue: 0x93931c13e507cbbcbf74d9eee4fb920eeaef84aa5110428da2eddb017d5ebcdd\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Neutrino81_4: 0xb2c81e3be60b809eebca250ae5f3958de8241f3c0942692d3cecd1fd00743211\ncaller: 0xf43414abb5a05c3037910506571e4333e16a4bf4\ncalldata_Neutrino81_0: 0x9cd460b500000000000000000000000000000000000000000000000000000000\ncalldatasize_Neutrino81: 0x4\n", "description": "A possible integer overflow exists in the function `passRepay(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/NTS_Crypto_Deposit-0.sol", "function": "passRepay(address)", "lineno": 236, "title": "Integer Overflow ", "type": "Warning"}, {"address": 6136, "code": "ayable onlyBoss2 {\n  ", "debug": "callvalue: 0x1000000000000000000000000000000000000000000000000\ncalldata_Neutrino81_0: 0xb60d428800000000000000000000000000000000000000000000000000000000\ncalldatasize_Neutrino81: 0x4\n", "description": "A possible integer overflow exists in the function `fund()`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/NTS_Crypto_Deposit-0.sol", "function": "fund()", "lineno": 226, "title": "Integer Overflow ", "type": "Warning"}, {"address": 6144, "code": "ayable onlyBoss2 {\n        uint256 v", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Neutrino81_0: 0xb60d428800000000000000000000000000000000000000000000000000000000\ncalldatasize_Neutrino81: 0x4\nstorage_8: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/NTS_Crypto_Deposit-0.sol", "function": "fund()", "lineno": 226, "title": "Exception state", "type": "Informational"}], "success": true}
