{"error": null, "issues": [{"address": 995, "code": "n getPendingCratesForUser(address _user) external view returns(uint[]) {\n        return addressToPurchasedBlocks[_u", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_NewCratePreSale_4: 0x800000000000000000000000000000000000000000000000000000000000000\ncalldata_NewCratePreSale_0: 0x7b2bff9d00000000000000000000000000000000000000000000000000000000\ncalldatasize_NewCratePreSale: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `getRobotsForUser(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/ETHERBOTS-11.sol", "function": "getRobotsForUser(address)", "lineno": 131, "title": "Integer Overflow ", "type": "Warning"}, {"address": 2366, "code": "   return expiredCrates[_user];\n    }\n\n", "debug": "The exception is triggered under the following conditions:\n\ncalldata_NewCratePreSale_32 + 4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_NewCratePreSale_4: 0x0\ncalldata_NewCratePreSale_0: 0x2f55745b00000000000000000000000000000000000000000000000000000000\ncalldatasize_NewCratePreSale: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETHERBOTS-11.sol", "function": "getPendingCrateForUserByIndex(address,uint256)", "lineno": 140, "title": "Exception state", "type": "Informational"}, {"address": 2583, "code": " whenNotPaused() {\n    requi", "debug": "", "description": "A possible transaction order independence vulnerability exists in function withdraw(). The value or direction of the call statement is determined from a tainted storage location", "filename": "/temp/ETHERBOTS-11.sol", "function": "withdraw()", "lineno": 206, "title": "Transaction order dependence", "type": "Warning"}, {"address": 2966, "code": "return addressToPurchasedB", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_NewCratePreSale_4: 0x8421003f084001f4210815cf88407c00000000000000037c1d000e8d178001f\ncalldata_NewCratePreSale_0: 0x7b2bff9d00000000000000000000000000000000000000000000000000000000\ncalldatasize_NewCratePreSale: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `getRobotsForUser(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/ETHERBOTS-11.sol", "function": "getRobotsForUser(address)", "lineno": 132, "title": "Integer Overflow ", "type": "Warning"}, {"address": 2968, "code": "return addressToPurchasedB", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_NewCratePreSale_4: 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb\ncalldata_NewCratePreSale_0: 0x7b2bff9d00000000000000000000000000000000000000000000000000000000\ncalldatasize_NewCratePreSale: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `getRobotsForUser(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/ETHERBOTS-11.sol", "function": "getRobotsForUser(address)", "lineno": 132, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3268, "code": "the number of expired crates for each user \n    // i.e. cra", "debug": "The exception is triggered under the following conditions:\n\ncalldata_NewCratePreSale_32 + 4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\ncalldata_NewCratePreSale_4: 0x0\ncalldata_NewCratePreSale_0: 0x88cca29500000000000000000000000000000000000000000000000000000000\ncalldatasize_NewCratePreSale: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETHERBOTS-11.sol", "function": "_function_0x88cca295", "lineno": 76, "title": "Exception state", "type": "Informational"}], "success": true}
