{"error": null, "issues": [{"address": 2107, "code": "ess[] public admins;\n\n ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_TulipToken_4: 0x0\nstorage_1: 0x0\ncalldata_TulipToken_0: 0x14bfd6d000000000000000000000000000000000000000000000000000000000\ncalldatasize_TulipToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Ether_Tulips-0.sol", "function": "_function_0x14bfd6d0", "lineno": 5, "title": "Exception state", "type": "Informational"}, {"address": 3003, "code": ";\n\ncontract Access", "debug": "storage_1: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x0\ncaller: 0x0\ncalldata_TulipToken_0: 0x7048027500000000000000000000000000000000000000000000000000000000\ncalldatasize_TulipToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `addAdmin(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Ether_Tulips-0.sol", "function": "addAdmin(address)", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3612, "code": "ic tulipToOwner;\n  ma", "debug": "The exception is triggered under the following conditions:\n\ncalldata_TulipToken_4: 0x0\nstorage_2: 0x0\ncalldata_TulipToken_0: 0xaf794a4f00000000000000000000000000000000000000000000000000000000\ncalldatasize_TulipToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Ether_Tulips-0.sol", "function": "_function_0xaf794a4f", "lineno": 60, "title": "Exception state", "type": "Informational"}, {"address": 3811, "code": ";\n\ncontract Access", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TulipToken_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncaller: 0x0\nstorage_keccac_calldata_TulipToken_32_+_4: 0x0\ncalldata_TulipToken_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_TulipToken_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_TulipToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transfer(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Ether_Tulips-0.sol", "function": "transfer(address,uint256)", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}, {"address": 4074, "code": "delete fromTulips[fromTulips.", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TulipToken_4: 0x1\ncalldata_TulipToken_32 + 36: 0x0\nstorage_keccac_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TulipToken_4 +\n0: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_TulipToken_4: 0x0\ncaller: 0x0\nstorage_keccac_calldata_TulipToken_32_+_36: 0x0\ncalldata_TulipToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_TulipToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_TulipToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Ether_Tulips-0.sol", "function": "transferFrom(address,address,uint256)", "lineno": 95, "title": "Exception state", "type": "Informational"}], "success": true}
