{"error": null, "issues": [{"address": 1424, "code": "openBlock, clottery.tot", "debug": "The exception is triggered under the following conditions:\n\nstorage_3: 0x0\ncalldata_SetLottery_0: 0x24a434eb00000000000000000000000000000000000000000000000000000000\ncalldatasize_SetLottery: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Hello_Dog-3.sol", "function": "openCarousel()", "lineno": 201, "title": "Exception state", "type": "Informational"}, {"address": 1927, "code": ";\n\ncontract DogCor", "debug": "storage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_3 +\n87903029871075914254377627908054574944891091886930582284385770809450030037079 +\n4*storage_3: 0xff00\nstorage_2 +\n87903029871075914254377627908054574944891091886930582284385770809450030037079 +\n4*storage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x0\ncalldata_SetLottery_0: 0x24a434eb00000000000000000000000000000000000000000000000000000000\ncalldatasize_SetLottery: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `openCarousel()`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Hello_Dog-3.sol", "function": "openCarousel()", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}, {"address": 2214, "code": "enes);\n        OpenCarousel(", "debug": "", "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.", "filename": "/temp/Hello_Dog-3.sol", "function": "openCarousel()", "lineno": 218, "title": "Message call to external contract", "type": "Informational"}, {"address": 2769, "code": "wId, clottery.luckyGene", "debug": "The exception is triggered under the following conditions:\n\nstorage_3: 0x0\ncalldata_SetLottery_4: 0x6\ncalldata_SetLottery_0: 0x27729e9300000000000000000000000000000000000000000000000000000000\ncalldatasize_SetLottery: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Hello_Dog-3.sol", "function": "openLottery(uint8)", "lineno": 145, "title": "Exception state", "type": "Informational"}, {"address": 3477, "code": ";\n\ncontract DogCor", "debug": "storage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nblock_number: 0x0\nstorage_1: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_3 +\n87903029871075914254377627908054574944891091886930582284385770809450030037079 +\n4*storage_3: 0xff00\nstorage_2 +\n87903029871075914254377627908054574944891091886930582284385770809450030037079 +\n4*storage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x0\ncalldata_SetLottery_4: 0x6\ncalldata_SetLottery_0: 0x27729e9300000000000000000000000000000000000000000000000000000000\ncalldatasize_SetLottery: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `openLottery(uint8)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Hello_Dog-3.sol", "function": "openLottery(uint8)", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}, {"address": 4909, "code": "eward); \n    }\n    \n    fun", "debug": "The exception is triggered under the following conditions:\n\ncalldata_SetLottery_4: 0xfffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe\nstorage_3: 0xfffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc\ncalldata_SetLottery_0: 0x760df4fe00000000000000000000000000000000000000000000000000000000\ncalldatasize_SetLottery: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Hello_Dog-3.sol", "function": "_isCarousal(uint256)", "lineno": 82, "title": "Exception state", "type": "Informational"}, {"address": 4966, "code": "rm() external view returns ", "debug": "The exception is triggered under the following conditions:\n\nstorage_3: 0x55fd9285e813eaffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_SetLottery_4: 0x55fd9285e813eb00000000000000000000000000000000000000000000000000\nstorage_3 +\n87903029871075914254377627908054574944891091886930582284385770809450030037075 +\n4*calldata_SetLottery_4: 0xff00\ncalldata_SetLottery_0: 0x760df4fe00000000000000000000000000000000000000000000000000000000\ncalldatasize_SetLottery: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Hello_Dog-3.sol", "function": "_isCarousal(uint256)", "lineno": 85, "title": "Exception state", "type": "Informational"}, {"address": 5427, "code": "ol(uint amount) publ", "debug": "", "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.", "filename": "/temp/Hello_Dog-3.sol", "function": "toLotteryPool(uint256)", "lineno": 76, "title": "Message call to external contract", "type": "Informational"}, {"address": 5572, "code": "m) external view retu", "debug": "", "description": "The contract account state is changed after an external call. Consider that the called contract could re-enter the function before this state change takes place. This can lead to business logic vulnerabilities.", "filename": "/temp/Hello_Dog-3.sol", "function": "toLotteryPool(uint256)", "lineno": 81, "title": "State change after external call", "type": "Warning"}, {"address": 5646, "code": "c finalLottery;\n    \n    uin", "debug": "The exception is triggered under the following conditions:\n\ncalldata_SetLottery_4: 0x0\nstorage_3: 0x0\ncalldata_SetLottery_0: 0xfa467f2700000000000000000000000000000000000000000000000000000000\ncalldatasize_SetLottery: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Hello_Dog-3.sol", "function": "_function_0xfa467f27", "lineno": 55, "title": "Exception state", "type": "Informational"}], "success": true}
