{"error": null, "issues": [{"address": 925, "code": "guardCounter);\n    }\n}\n\n// File", "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 1117\n", "filename": "/temp/My_Crypto_Heroes-21.sol", "function": "_function_0x89476069", "lineno": 1265, "title": "Multiple Calls", "type": "Information"}, {"address": 1117, "code": "   require(localCounter == _guardCounter);\n    }\n}\n\n// File:", "debug": "", "description": "This contract executes a message call to an address provided as a function argument. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.", "filename": "/temp/My_Crypto_Heroes-21.sol", "function": "_function_0x89476069", "lineno": 1265, "title": "Message call to external contract", "type": "Warning"}], "success": true}
