{"error": null, "issues": [{"address": 6191, "debug": "callvalue: 0x57f25cd000000000000000000000000000000000000000000000000000000000\nstorage_18: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncalldatasize_SnailFarm3: 0x3\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/SnailFarm_3-0.sol", "function": "fallback", "lineno": 927, "title": "Integer Overflow ", "type": "Warning"}, {"address": 6204, "debug": "The exception is triggered under the following conditions:\n\nstorage_18: 0x1\ncallvalue: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldatasize_SnailFarm3: 0x3\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/SnailFarm_3-0.sol", "function": "fallback", "lineno": 927, "title": "Exception state", "type": "Informational"}, {"address": 9163, "code": "  emit St", "debug": "", "description": "Function BuyStartingSnail() retrieves the transaction origin (tx.origin) using the ORIGIN opcode. Use msg.sender instead.\nSee also: https://solidity.readthedocs.io/en/develop/security-considerations.html#tx-origin", "filename": "/temp/SnailFarm_3-0.sol", "function": "BuyStartingSnail()", "lineno": 509, "title": "Use of tx.origin", "type": "Warning"}, {"address": 28170, "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_SnailFarm3_0: 0x1a1d28aa00000000000000000000000000000000000000000000000000000000\ncalldatasize_SnailFarm3: 0x4\nstorage_16: 0x0\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/SnailFarm_3-0.sol", "function": "ClaimAcornShare()", "lineno": 927, "title": "Exception state", "type": "Informational"}], "success": true}
