{"error": null, "issues": [{"address": 10568, "code": "\n    /**\n     ", "debug": "The exception is triggered under the following conditions:\n\ntimestamp: 0x0\nstorage_14: 0x1\ncalldata_StarCards_0: 0x55de5a9300000000000000000000000000000000000000000000000000000000\ncalldatasize_StarCards: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Star_Cards-0.sol", "function": "getCurrentEdition()", "lineno": 48, "title": "Exception state", "type": "Informational"}, {"address": 11859, "code": "ility library ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_StarCards_4: 0x0\nstorage_3 + keccac_calldata_StarCards_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_7: 0x1\ncalldata_StarCards_0: 0x181e012400000000000000000000000000000000000000000000000000000000\ncalldatasize_StarCards: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Star_Cards-0.sol", "function": "getRemainingTime(uint256)", "lineno": 61, "title": "Exception state", "type": "Informational"}], "success": true}
